eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
server:
  port: 4018
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/360gunner/pfe-config-docker.git
  application:
    name: config-server